apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: artifactory
  labels:
    app: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
     app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
      annotations:
        kubernetes.io/change-cause: "Update to 6.15.1"           
    spec:
      containers:
      - name: artifactory
        image: docker.bintray.io/jfrog/artifactory-pro:6.15.1
        ports:
        - containerPort: 8081
          name: http
        livenessProbe:
          httpGet:
            path: '/artifactory/webapp/#/login'
            port: 8081
          initialDelaySeconds: 180
          failureThreshold: 10
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: '/artifactory/webapp/#/login'
            port: 8081
          initialDelaySeconds: 60
          failureThreshold: 10
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
---          
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: default
  labels:
    app: artifactory
spec:
  selector:
    app: artifactory
  ports:
  - name: http
    port: 8081
    targetPort: http  