apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: artifactory
  labels:
    app: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
     app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
      annotations:
        # sidecar.istio.io/rewriteAppHTTPProbers: "true"      
        kubernetes.io/change-cause: "Update to 6.16.0"           
    spec:
      containers:
      - name: artifactory
        image: docker.bintray.io/jfrog/artifactory-pro:6.16.0
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 15020
          name: ready          
        resources: 
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"          
        # readinessProbe:
        #   httpGet:
        #     path: '/healthz/ready'
        #     port: 15020
        #   initialDelaySeconds: 60
        #   failureThreshold: 10
        #   timeoutSeconds: 10
        #   periodSeconds: 10
        #   successThreshold: 1
        # livenessProbe:
        #   httpGet:
        #     path: '/artifactory/webapp/#/login'
        #     port: 15020
        #   initialDelaySeconds: 90
        #   failureThreshold: 10
        #   timeoutSeconds: 10
        #   periodSeconds: 10
        #   successThreshold: 1         
        # startupProbe:
        #   httpGet:
        #     path: '/artifactory/webapp/#/login'
        #     port: 8081
        #   initialDelaySeconds: 120
        #   failureThreshold: 10
        #   timeoutSeconds: 10
        #   periodSeconds: 10
        #   successThreshold: 1            
---          
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: default
  labels:
    app: artifactory
spec:
  selector:
    app: artifactory
  ports:
  - name: http
    port: 8081
    targetPort: http  