---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mywebserver
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: mywebserver
  chart:
    git: ssh://git@github.com/mendrugory/flux-poc
    ref: master
    path: charts/mywebserver
  values:
    image: 
      name: httpd 
      tag: latest